pipeline:
  name: pipe2
  identifier: pipe2
  projectIdentifier: RaghavTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: pipe
        identifier: pipe
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: cidelegate
              namespace: harness-qa-delegate
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: run
                  identifier: run
                  spec:
                    connectorRef: docker
                    image: alpine
                    shell: Sh
                    command: echo run
  properties:
    ci:
      codebase:
        connectorRef: sshdev
        build: <+input>
