pipeline:
  identifier: Build_devkimittal_CI3574_1703173804940
  name: Build CI3574
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1703173792119
        repoName: devkimittal/CI3574
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - parallel:
                  - step:
                      identifier: echo
                      name: echo
                      spec:
                        shell: Sh
                        command: |-
                          sleep 20
                          echo "______"
                          docker ps
                          sleep 2
                          echo "______"
                          docker ps
                          sleep 2
                          echo "______"
                          docker ps
                          sleep 2
                          echo "______"
                          docker ps
                          sleep 2
                          echo "______"
                          docker ps
                          sleep 2
                      timeout: ""
                      type: Run
                  - step:
                      type: Run
                      name: Run_2
                      identifier: Run_2
                      spec:
                        connectorRef: account.harnessImage
                        image: alpine
                        shell: Sh
                        command: sleep 400
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        strategy:
          parallelism: 1
